title = "Amadiff"
disabled = false
languageCode = "en"
languageName = "English"

[params]
  displayName = "EN"
  isoCode = "en"
  dateFormat = "2 January 2006"
  logo = "amadiff-logo.png"
  description = "An open source browser extension to diversify how you can view Github diffs."
