# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.

[[main]]
  name = "Privacy Policy"
  pageRef = "/privacy-policy"
  weight = 10

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/andersonaddo/amadiff"
  weight = 20
