baseURL = "/"
languageCode = 'en-us'
theme = 'terminal'
title = "BetterDiffs"
keywords = ""
copyright = ""

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 10
  fullWidthTheme = false
  centerTheme = true
  subtitle = "Experience better commit diffs directly in Github!"


[params.logo]
    logoText = "BetterDiffs"
    logoHomeLink = "/"

[menu]
    [[menu.main]]
    identifier = "privacy-policy"
    name = "Privacy Policy"
    url = "/privacy-policy"

    [[menu.main]]
    identifier = "repo"
    name = "Github"
    url = "https://github.com/andersonaddo/betterdiffs"
