
title: BetterDiffs
description: Experience better commit diffs directly in Github!
remote_theme: jekyll/minima@1e8a445 # https://github.com/jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: solarized-dark